services:
  - name: wordcloud-backend
    type: web
    runtime: python
    repo: https://github.com/tahayparker/wordcloud
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootdir: wordcloud-website/backend
    envVars:
      - key: FLASK_ENV
        value: production